
CREATE TABLE LOAN (
ID BIGINT NOT NULL  AUTO_INCREMENT,
BOOK_COPY_ID BIGINT NOT NULL, -- Foreign key to book COPY table(ben)
USER_ID BIGINT NOT NULL,
ISSUE_DATE DATE NOT NULL,
DUE_DATE DATE NOT NULL,
RETURNED_DATE DATE,
PRIMARY KEY (ID),
FOREIGN KEY (BOOK_COPY_ID) REFERENCES BOOK_COPY(ID),
FOREIGN KEY (USER_ID) REFERENCES USER(ID)
)

